plugins {
	id 'fabric-loom' version '1.4.1'
	id 'maven-publish'
	id 'com.github.johnrengelman.shadow' version '8.1.1'
}

java {
	sourceCompatibility = JavaVersion.VERSION_17
	targetCompatibility = JavaVersion.VERSION_17
	withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
	options.release = 17
}
base {
	archivesName = project.archives_base_name
}
version = project.mod_version
group = project.maven_group

configurations {
	shadow
	implementation.extendsFrom shadow
}

dependencies {
	minecraft "com.mojang:minecraft:1.20.1"
	mappings "net.fabricmc:yarn:1.20.1+build.10:v2"
	modImplementation "net.fabricmc:fabric-loader:0.18.4"

	modImplementation "net.fabricmc.fabric-api:fabric-api:0.92.7+1.20.1"

	shadow files('lib/vboxjws.jar')
	implementation files("libs/vboxjws.jar")
	
	include files("libs/vboxjws.jar")

	
	implementation "com.sun.xml.ws:jaxws-rt:2.3.7"
	include "com.sun.xml.ws:jaxws-rt:2.3.7"
	include "javax.xml.ws:jaxws-api:2.3.1"
	include "javax.xml.bind:jaxb-api:2.3.1"
	include "javax.jws:javax.jws-api:1.1"
	include "com.sun.istack:istack-commons-runtime:3.0.12"
	include "org.jvnet.staxex:stax-ex:1.8.3"
	include "com.sun.xml.fastinfoset:FastInfoset:1.2.18"
	include "org.jvnet.mimepull:mimepull:1.9.15"
	include "com.sun.xml.messaging.saaj:saaj-impl:1.5.3"
	include "jakarta.xml.soap:jakarta.xml.soap-api:1.4.2"
	include "com.sun.xml.stream.buffer:streambuffer:2.0.1"
	include "com.sun.xml.ws:policy:2.7.10"
	include "org.glassfish.gmbal:gmbal-api-only:4.0.3"
	include "org.glassfish.ha:ha-api:3.1.13"
	include "org.glassfish.external:management-api:3.2.3"
	include "org.glassfish.jaxb:jaxb-runtime:2.3.7"
	include "org.glassfish.jaxb:txw2:2.3.7"
	include "com.sun.activation:jakarta.activation:1.2.2"
}
shadowJar {
	configurations = [project.configurations.shadow]
	archiveBaseName = "${project.archives_base_name}"
	archiveClassifier = 'dev-shadow'
	archiveVersion = "${project.mod_version}"
}

remapJar {
	dependsOn shadowJar
	inputFile = shadowJar.archiveFile
	archiveClassifier = ''
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
	options.release = 17
}

jar {
	from "LICENSE"
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			artifact(remapJar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	repositories {
		
	}
}