modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/FasterBranch527/new-vm-computers/issues"

[[mods]]
modId="mcvmcomputers"
version="${version}"
displayName="New VM Computers"
displayURL="https://modrinth.com/mod/new-vm-computers"
logoFile="icon.png"
authors="DeltaTwoForce, FB527"
description='''
Build computers that actually work using the VirtualBox API!, Now in MC 1.20.1
'''

[[dependencies.mcvmcomputers]]
	modId="forge"
	mandatory=true
	versionRange="[47,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.mcvmcomputers]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.1,1.20.2)"
	ordering="NONE"
	side="BOTH"
