modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="newvmcomputers"
version="${version}"
displayName="*NEW* VM Computers"
logoFile="assets/newvmcomputers/icon.png"
authors="DeltaTwoForce, FB527"
description='''
Build computers that actually work using the VirtualBox API! Now on 1.20.1!
'''

[[dependencies.newvmcomputers]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.newvmcomputers]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.newvmcomputers]]
modId="flamingo"
mandatory=false
versionRange="*"
ordering="NONE"
side="BOTH"